Feat: Add Navbar component
Lebanon-WBC-Capstones/real-generosity-web pull request #15
Opened 2021-02-15 17:52 UTC by JosephTarrazi

resolves #3

2021-02-15 20:54 UTC, Skia69 requested changes
Please, take into consideration the comments I dropped below

2021-02-15 20:54 UTC, Skia69 commented on src/components/NavBar/NavBar.jsx
> +            Montserrat"
This won't have any effect - removing it is advisable

2021-02-15 20:54 UTC, Skia69 commented on src/components/NavBar/NavBar.jsx
> +        fontSize={16}
Please use the proper theme token provided to you by chakra UI in which case it's fontSize='md'

2021-02-15 20:54 UTC, Skia69 commented on src/components/NavBar/NavBar.jsx
> +        fontWeight={600}
Please use the proper theme token provided to you by chakra UI in which case it's fontWeight='medium'

2021-02-15 20:54 UTC, Skia69 commented on src/components/NavBar/NavBar.jsx
> +        bg="transparent"
The navbar background is transparent by default - this is redundant

2021-02-15 20:54 UTC, Skia69 commented on src/components/NavBar/NavBar.jsx
> +        <Box fontSize={24}>LOGO</Box>
Please use the proper theme token provided to you by chakra UI in which case it's fontSize='2xl'

2021-02-15 20:54 UTC, Skia69 commented on src/components/NavBar/NavBar.jsx
> +          </Menu>
This code snippet needs quite a bit of refactoring:

- MenuList has a default "min-width: 14rem" which is far larger than the actual content itself. A quick fix would be to pass the following prop explicitly: minW="max-content"

2021-02-15 20:54 UTC, Skia69 commented on src/components/NavBar/NavBar.jsx
> +              p={1}
p={2} will make the button look quite better

2021-02-15 20:54 UTC, Skia69 commented on src/pages/HomePage.jsx
> +      <NavBar />
NavBar should reside in App.js since it's presumably going to be present in every single page

2021-02-16 07:53 UTC, adlogi commented
Thank you @JosephTarrazi . It looks good. You can quickly resolve Mhammad's comments and it'd be ready to merge. Please add .eslintcache to .gitignore.

2021-02-16 10:30 UTC, adlogi approved these changes

2021-02-16 14:02 UTC, merged