Feat: add Carousel
Lebanon-WBC-Capstones/real-generosity-web pull request #19
Opened 2021-02-16 15:23 UTC by Samsamargi

2021-02-17 12:48 UTC, Skia69 commented
There's way too many conflicts in this branch - @Samsamargi and I decided to close this PR and create a fresh new branch

2021-02-18 12:27 UTC, adlogi requested changes
Please check the comments above.

2021-02-18 12:27 UTC, adlogi commented on src/styles.css
> +}
Why do you need to style .App when you're only working on a carousel? I suggest removing these.

2021-02-18 12:27 UTC, adlogi commented on .eslintcache
> +[{"C:\\Users\\user\\OneDrive\\Desktop\\Capstone Project\\Coding Part\\real-generosity-web\\src\\reportWebVitals.js":"1","C:\\Users\\user\\OneDrive\\Desktop\\Capstone Project\\Coding Part\\real-genero
Please add .eslintcache to .gitignore

2021-02-18 12:27 UTC, adlogi commented on src/components/Card.js
> +export default Card;
Is this the same component that @marwa-shahal created? If yes, please merge her branch into yours to use her code instead of simply copy it.

2021-02-18 12:27 UTC, adlogi commented on src/components/CardList.js
> +export default CardList;
I thought we agreed on building a carousel, but this seems to be a simple list. Is this an intended design change?

2021-02-22 15:17 UTC, closed without merging