Feat: add edit profile page
Lebanon-WBC-Capstones/real-generosity-web pull request #66
Opened 2021-02-22 11:38 UTC by fatima-katrib

Resolve #40

2021-02-23 08:56 UTC, adlogi requested changes

2021-02-23 08:56 UTC, adlogi commented on src/pages/EditProfile/EditProfile.jsx
> +    const [fullName, setFullName] = useState('');
I think we need separate fields/states for firstName and lastName instead of one fullName. You need also states to handle the profile and id images.

2021-03-03 05:27 UTC, adlogi commented
@fatima-katrib any updates on this?

2021-03-03 08:06 UTC, fatima-katrib commented
> @fatima-katrib any updates on this?

updated in a new branch you merged today. i removed the profile pic, handled the state of the id and did small changes in the design

2021-03-03 10:10 UTC, closed without merging